### ISSUE TITLE
Previous lines get deleted when editing the previous line in the repl

### ISSUE THREAD

**Issue by Akeboshiwind** [candid82/joker#190] opened 2019-03-16 19:10 UTC
This is a bit of a confusing issue but I'll try to do my best to describe it.

First off I'm on MacOS using iTerm2 with tmux if that matters with joker version v0.12.1.

Steps to reproduce:
1. Start up the joker repl
2. Enter a line in the repl such that the line overflows onto the next line in the repl. For example:
    ```clojure
    (println "some long test string<imagine the terminal ends here>
    that overflows the line")
    ```
3. Use the left arrow key to navigate back to the first line
4. Observe that each time you press left the previous line is deleted in the terminal

No newline is entered in the string in the repl above, this is when the line overflows because the line is wider than the terminal is.

**Comment by jcburley** [comment] 2019-03-16 19:39
Reproduced on Ubuntu.

This might be https://github.com/chzyer/readline/issues/169#issue-419284880 or similar -- probably not a Joker issue per se.

The `--no-readline` option avoids calling `readline()`, if that's useful; but, at that point, arrowing back doesn't work at all.

**Comment by candid82** [comment] 2019-03-17 01:34
I can reproduce this on my machine as well (MacOS, iTerm2, no tmux). I am pretty sure this is readline issue. Seems pretty minor too. Until this is fixed in readline and if this is causing problems for you I recommend using rlwrap instead: `rlwrap joker --no-readline`.

**Comment by candid82** [comment] 2019-03-22 05:40
Closing since it's not actionable until `readline` is fixed and has very low impact.

**Closed by candid82** 2019-03-22 05:40 UTC
